Issue 2 further db improvements
artofimagination/mysql-user-db-go-interface pull request #5
Opened 2020-11-18 22:27 UTC by artofimagination

Need to merge #4 before checking this

2020-11-23 06:25 UTC, pongi1987 requested changes

2020-11-23 06:25 UTC, pongi1987 commented on main.go
> +	mysqldb.DBConnection = "root:123secure@tcp(user-db:3306)/user_database?parseTime=true"
Pwd in the code  🤦‍♂️

2020-11-23 06:25 UTC, pongi1987 commented on models/product.go
> +	Public  bool      `validation:"required"`
Simple bool couldn't be omited or required.
If you really would like to make bool values required, you should use pointers here:
```suggestion
	Public  *bool      `validation:"required"`
```

2020-11-23 06:25 UTC, pongi1987 commented on mysqldb/products_test.go
> +	"github.com/artofimagination/mysql-user-db-go-interface/models"
Are you using `goimports`?

2020-11-29 22:11 UTC, closed without merging

2020-11-29 22:12 UTC, artofimagination commented
Not needed since reworks in #7